export const questions = [
  {
    id: 1,
    question: "What does HTML stand for?",
    options: [
      "Hyper Text Markup Language",
      "Hyperlinks and Text Markup Language",
      "Home Tool Markup Language",
      "Hyper Tool Markup Language",
    ],
    correct_answer: "Hyper Text Markup Language",
  },
  {
    id: 2,
    question: "What does CSS stand for?",
    options: [
      "Cascading Style Sheets",
      "Colorful Style Sheets",
      "Creative Style Sheets",
      "Computer Style Sheets",
    ],
    correct_answer: "Cascading Style Sheets",
  },
  {
    id: 3,
    question: "What does API stand for?",
    options: [
      "Application Programming Interface",
      "Advanced Programming Interface",
      "Automated Programming Interface",
      "Application Program Interface",
    ],
    correct_answer: "Application Programming Interface",
  },
  {
    id: 4,
    question: "Which symbol is used to denote a class in CSS?",
    options: ["#", ".", "$", "@"],
    correct_answer: ".",
  },
  {
    id: 5,
    question: "What is the capital of France?",
    options: ["Berlin", "Paris", "Madrid", "Rome"],
    correct_answer: "Paris",
  },
  {
    id: 6,
    question: "Who is the author of 'To Kill a Mockingbird'?",
    options: ["Harper Lee", "J.K. Rowling", "Stephen King", "Mark Twain"],
    correct_answer: "Harper Lee",
  },
  {
    id: 7,
    question: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Jupiter", "Saturn"],
    correct_answer: "Mars",
  },
  {
    id: 8,
    question: "What is the chemical symbol for water?",
    options: ["H2O", "CO2", "O2", "H2SO4"],
    correct_answer: "H2O",
  },
  {
    id: 9,
    question: "Who painted the Mona Lisa?",
    options: [
      "Leonardo da Vinci",
      "Vincent van Gogh",
      "Pablo Picasso",
      "Michelangelo",
    ],
    correct_answer: "Leonardo da Vinci",
  },
  {
    id: 10,
    question: "Which country is famous for its tulips?",
    options: ["Netherlands", "Italy", "France", "Germany"],
    correct_answer: "Netherlands",
  },
  {
    id: 11,
    question: "What is the square root of 64?",
    options: ["6", "8", "10", "12"],
    correct_answer: "8",
  },
  {
    id: 12,
    question: "What is the tallest mammal?",
    options: ["Elephant", "Giraffe", "Horse", "Whale"],
    correct_answer: "Giraffe",
  },
  {
    id: 13,
    question: "Who wrote 'Romeo and Juliet'?",
    options: [
      "William Shakespeare",
      "Charles Dickens",
      "Jane Austen",
      "F. Scott Fitzgerald",
    ],
    correct_answer: "William Shakespeare",
  },
  {
    id: 14,
    question: "Which continent is the largest by land area?",
    options: ["Africa", "Asia", "North America", "Europe"],
    correct_answer: "Asia",
  },
  {
    id: 15,
    question: "What is the chemical symbol for gold?",
    options: ["Ag", "Au", "Pt", "Hg"],
    correct_answer: "Au",
  },
  {
    id: 16,
    question: "Which instrument is used to measure earthquakes?",
    options: ["Seismograph", "Barometer", "Thermometer", "Hygrometer"],
    correct_answer: "Seismograph",
  },
  {
    id: 17,
    question: "What is the national animal of China?",
    options: ["Giant Panda", "Dragon", "Red-crowned Crane", "Tiger"],
    correct_answer: "Giant Panda",
  },
  {
    id: 18,
    question: "Who developed the theory of relativity?",
    options: [
      "Isaac Newton",
      "Albert Einstein",
      "Galileo Galilei",
      "Stephen Hawking",
    ],
    correct_answer: "Albert Einstein",
  },
  {
    id: 19,
    question: "What is the capital of Japan?",
    options: ["Seoul", "Beijing", "Tokyo", "Bangkok"],
    correct_answer: "Tokyo",
  },
  {
    id: 20,
    question: "What is the smallest prime number?",
    options: ["0", "1", "2", "3"],
    correct_answer: "2",
  },
  {
    id: 21,
    question: "Who wrote '1984'?",
    options: [
      "George Orwell",
      "F. Scott Fitzgerald",
      "Ernest Hemingway",
      "J.K. Rowling",
    ],
    correct_answer: "George Orwell",
  },
  {
    id: 22,
    question: "What is the chemical symbol for sodium?",
    options: ["Na", "So", "Sn", "Ni"],
    correct_answer: "Na",
  },
  {
    id: 23,
    question: "Which planet is known as the 'Morning Star'?",
    options: ["Mercury", "Venus", "Mars", "Jupiter"],
    correct_answer: "Venus",
  },
  {
    id: 24,
    question: "What is the largest organ in the human body?",
    options: ["Liver", "Skin", "Heart", "Lung"],
    correct_answer: "Skin",
  },
  {
    id: 25,
    question: "Who painted 'The Starry Night'?",
    options: [
      "Vincent van Gogh",
      "Pablo Picasso",
      "Leonardo da Vinci",
      "Claude Monet",
    ],
    correct_answer: "Vincent van Gogh",
  },
  {
    id: 26,
    question: "What is the chemical formula for ozone?",
    options: ["O2", "O3", "CO2", "H2O"],
    correct_answer: "O3",
  },
  {
    id: 27,
    question: "What is the tallest mountain in the world?",
    options: ["Mount Everest", "K2", "Kangchenjunga", "Lhotse"],
    correct_answer: "Mount Everest",
  },
  {
    id: 28,
    question: "Who discovered penicillin?",
    options: [
      "Alexander Fleming",
      "Marie Curie",
      "Albert Einstein",
      "Isaac Newton",
    ],
    correct_answer: "Alexander Fleming",
  },
  {
    id: 29,
    question: "What is the capital of Australia?",
    options: ["Sydney", "Melbourne", "Canberra", "Perth"],
    correct_answer: "Canberra",
  },
  {
    id: 30,
    question: "Who composed 'The Four Seasons'?",
    options: [
      "Wolfgang Amadeus Mozart",
      "Johann Sebastian Bach",
      "Antonio Vivaldi",
      "Ludwig van Beethoven",
    ],
    correct_answer: "Antonio Vivaldi",
  },
  {
    id: 31,
    question: "What is the chemical symbol for iron?",
    options: ["Ir", "Fe", "In", "Au"],
    correct_answer: "Fe",
  },
  {
    id: 32,
    question: "Who wrote 'Pride and Prejudice'?",
    options: [
      "Jane Austen",
      "Emily Brontë",
      "Charlotte Brontë",
      "Charles Dickens",
    ],
    correct_answer: "Jane Austen",
  },
  {
    id: 33,
    question: "What is the capital of Brazil?",
    options: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador"],
    correct_answer: "Brasília",
  },
  {
    id: 34,
    question: "What is the chemical symbol for silver?",
    options: ["Ag", "Si", "Sv", "Au"],
    correct_answer: "Ag",
  },
  {
    id: 35,
    question: "Who was the first person to step on the moon?",
    options: [
      "Neil Armstrong",
      "Buzz Aldrin",
      "Yuri Gagarin",
      "Michael Collins",
    ],
    correct_answer: "Neil Armstrong",
  },
  {
    id: 36,
    question: "What is the currency of Japan?",
    options: ["Yuan", "Euro", "Yen", "Won"],
    correct_answer: "Yen",
  },
  {
    id: 37,
    question: "What is the chemical symbol for carbon?",
    options: ["Co", "Ca", "C", "Cb"],
    correct_answer: "C",
  },
  {
    id: 38,
    question: "Who painted 'The Last Supper'?",
    options: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello"],
    correct_answer: "Leonardo da Vinci",
  },
  {
    id: 39,
    question: "Which planet is known as the 'Red Planet'?",
    options: ["Venus", "Mars", "Jupiter", "Saturn"],
    correct_answer: "Mars",
  },
  {
    id: 40,
    question: "Who is the current CEO of Tesla?",
    options: ["Elon Musk", "Jeff Bezos", "Tim Cook", "Mark Zuckerberg"],
    correct_answer: "Elon Musk",
  },
];
